// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkwchDsoHm8FG-ybKGHxg2wl0-gt8uZwI',
    appId: '1:863539075914:web:e3c91ca536d5c37f68ffb3',
    messagingSenderId: '863539075914',
    projectId: 'servicemenphoneapp',
    authDomain: 'servicemenphoneapp.firebaseapp.com',
    storageBucket: 'servicemenphoneapp.firebasestorage.app',
    measurementId: 'G-NB2G7FDRKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlWW6s8MTeTp5ZX1eX788FjENDO4slZK4',
    appId: '1:170197394220:android:8ffc04cd71fd243be2c289',
    messagingSenderId: '170197394220',
    projectId: 'servicemenapplication4-2026',
    storageBucket: 'servicemenapplication4-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEENkFN50WS_yRvD1YxV4b8a6BalFFGEg',
    appId: '1:863539075914:ios:b4047f52004a44cc68ffb3',
    messagingSenderId: '863539075914',
    projectId: 'servicemenphoneapp',
    storageBucket: 'servicemenphoneapp.firebasestorage.app',
    iosBundleId: 'com.pakservice.marketplace.pakServiceMarketplace',
  );
}
